#!/bin/sh
#
# Start the 433ctrl service.
#
### BEGIN INIT INFO
# Provides:          433ctrl
# Required-Start:    $local_fs $syslog
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: 433ctrl
# Description:       433ctrl
### END INIT INFO

dir=/root/433ctrl
name=433ctrl
ctrl=$dir/$name
log=/var/log/433ctrl.log

. /lib/lsb/init-functions

case "$1" in
    start)
	log_begin_msg "Starting 433ctrl service..."
	$ctrl >> $log 2>&1 &
	log_end_msg $?
	;;
    stop)
	log_begin_msg "Stopping 433ctrl service..."
	killall $name
	log_end_msg $?
	;;
    *)
	echo "$0 {start|stop}"
	;;
esac
